### ISSUE TITLE
Create a root node implementation in CPP

### ISSUE THREAD

**Issue by abossenbroek** [abossenbroek/GeneralTree#53]

**Comment by abossenbroek** [comment]
# Architecture

The root node should remain a `R6` object. Instead of using a single object to represent every node on the tree, the data will be stored at the root level with hash tables. This way a considerable amount of time can be saved because memory access will be more straight forward.

## Data

The root node will require the following hash tables:
- `internal_node_id` to `left_child`
- `internal_node_id` to `siblings`
- `internal_node_id` to `id`
- `internal_node_id` to `data`

by keeping a list of unique internal numbers we can keep the memory overhead to a minimum.

## Internal representation and Saving to disk

We start first with creating an object that cannot be saved to disk. This object is a C++ pointer in R. This will permit to develop faster since we are not required to write `<>as()` and `wrap()` functions for each implementation. Once we settle on a final implementation we will write a function that permits to serialize the C++ object to a R object.
- [x] Rewrite first try at C++ implementation 9f6a62ebfeef11c1bbbcf78bf6c38de14af48ef6 to `XPtr` see the [Rcpp post on this](http://romainfrancois.blog.free.fr/index.php?post/2010/01/08/External-pointers-with-Rcpp) **done in:** 57e3b7b343c60bab7888a03ef18cacdc3805323b
- [ ] ❕ write a function that serializes the C++ object to a R object.

## Testing
- [x] ❗ Write tests in Catch to test the functionality build into 9f6a62ebfeef11c1bbbcf78bf6c38de14af48ef6 **done in:** 03c709c182803fade10e683b0b5cba197b767030 

## Challenges

One of the key challenges to port the current implementation to C++ is that C++ requires to know the type of each value before storing it. For this reason we first seek to implement a tree where the key is an string.
- [ ] implement data value as list or environment (chose for specific based on memory footprint)
- [ ] decide whether to use `boost::variant` or `boost::any` to store data types

### Considerations

#### Integer key

The problem with integer keys is that when an integer is converted from R to C++ it becomes a floating point number with a mantissa of 53. This could become a problem on the long term. For now we will settle with a string key for testing.
- [ ] ❕  test whether string key handles UTF-8 characters correctly.

## Advanced key value

The difficulty for more advanced key value storage is that a compare function is required. We could implement compare functions for various native types and permit more exotic types with a user provided compare function.

# Tasks
- [x] write test to verify whether nodes can be added under each other. Done in 6027aa481ec48b8b36ed32f5f6cb0424f36c7373
- [x] improve function to ensure that a node has siblings. 3c347d1b3bd847c20632469958ea2a0ba7f2c6d5
- [ ] write test that verify whether adding multiple siblings work.
- [ ] write print function
- [ ] write R interface to addNode
- [ ] write R interface to find node and return value
- [ ] write R interface to find node and return a node on which can be added
- [ ] refactor methods
